### ISSUE TITLE
player.getAvailableAudio() and player.subtitles.list() returns empty array on macOS Safari browser

### ISSUE THREAD

**Issue by aditya43** [bitmovin/bitmovin-player-web-samples#43] opened 2020-05-25 12:33 UTC
Hello,

Following 2 APIs returning empty array on macOS Safari browser.

- player.getAvailableAudio();
- player.subtitles.list();

Same 2 methods are working fine on other browsers and returning expected data.
Issue is specifically on macOS Safari browser.

Kindly Help

**Comment by dweinber** [comment] 2020-05-25 12:40
Hi @aditya43,
Thanks for reaching out. This doesn't seem to be a problem with one of the provided samples here, therefore I'm going to close this issue. Please submit a support ticket using https://bitmovin.com/dashboard/support/cases/create

This issue might be related to your streams because I was not able to reproduce this problem so far. Please be sure to include the stream you are using in your support ticket.

**Closed by dweinber** 2020-05-25 12:40 UTC
